name: Build and Push Docker Image

on:
  #schedule:
  #  - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

env:
  # Default to GitHub repo name, but allows to set a separate docker repo name
  DOCKER_REPO: ${{ secrets.DOCKER_REPO || github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to DockerHub using stored credentials
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Get the latest available jotta-cli version from APT
      - name: Get latest jotta-cli version
        run: |
          VERSION=$(apt-cache madison jotta-cli | awk '{print $3}' | sort -V | tail -n1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Get the latest pushed Docker image version from Docker Hub
      # This uses the tag names, and excludes the "latest" tag
      - name: Get latest published Docker image version
        run: |
          DOCKER_VERSION=$(curl -s "https://registry.hub.docker.com/v2/repositories/bluet/jottacloud/tags" | \
            jq -r '.results[].name' | grep -v '^latest$' | awk -F '-' '{print $1}' | sort -V | tail -n1)
          echo "DOCKER_VERSION=$DOCKER_VERSION" >> $GITHUB_ENV

      # Compare versions; exit early if no update is needed
      - name: Compare versions and decide whether to build
        run: |
          if [ "${{ env.VERSION }}" == "${{ env.DOCKER_VERSION }}" ]; then
            echo "No update needed. Exiting."
            exit 0
          else
            echo "New version detected: ${{ env.VERSION }} (Latest Docker version: ${{ env.DOCKER_VERSION }})"
          fi

      # Enable QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Enable Buildx for advanced Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push the Docker image for multiple platforms
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64/v8 \
            -t ${{ env.DOCKER_REPO }}:latest \
            -t ${{ env.DOCKER_REPO }}:${{ env.VERSION }} \
            --push .

      # Tag the Git repository with the new version and push the tag
      - name: Tag and push Git version
        run: |
          git tag "${{ env.VERSION }}" -a -m "jotta-cli ${{ env.VERSION }}"
          git push --tags
